name: CI

on:
  pull_request:
    branches:
      - "trunk"

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
  
  collect:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - run: true
