name: Lint package

on:
  workflow_call:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
          - release-snapshot

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: conao3/setup-cask@master
        with:
          version: snapshot

      - name: Lint
        run: make package_lint