name: Test and release

env:
  NIXPKGS_REF: github:NixOS/nixpkgs/nixpkgs-unstable

on:
  push:
    branches:
      - "trunk"

jobs:
  lint:
    uses: ./.github/workflows/package_lint.yaml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  compare_versions:
    runs-on: ubuntu-latest
    needs: [lint, test]
    outputs:
      current_version: ${{ steps.gen_versions.outputs.CURRENT_VERSION }}
      next_version: ${{ steps.gen_versions.outputs.NEXT_VERSION }}
      bump: ${{ steps.gen_versions.outputs.DO_BUMP }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v22

      - name: Install dependencies
        run: |
          nix profile install ${{ env.NIXPKGS_REF }}#convco
      
      - id: gen_versions
        run: |
          CURRENT_VERSION=$(convco version)
          NEXT_VERSION=$(convco version -b)
          
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_ENV"
          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_ENV"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_OUTPUT"

          if [[ "$CURRENT_VERSION" == "$NEXT_VERSION" ]]; then
            echo "DO_BUMP=false" >> "$GITHUB_ENV"
            echo "DO_BUMP=false" >> "$GITHUB_OUTPUT"
          else
            echo "DO_BUMP=true" >> "$GITHUB_ENV"
            echo "DO_BUMP=true" >> "$GITHUB_OUTPUT"
          fi

  bump_and_release:
    if: needs.compare_versions.outputs.bump == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: compare_versions
    env:
      CURRENT_VERSION: ${{needs.compare_versions.outputs.current_version}}
      NEXT_VERSION: ${{needs.compare_versions.outputs.next_version}}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v22

      - name: Install dependencies
        run: |
          nix profile install ${{ env.NIXPKGS_REF }}#convco
      
      - name: Configure Git credentials
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Generate changelog
        run: |
          convco changelog \
            -m 1 \
            -u v${{ env.NEXT_VERSION }} \
            --include-hidden-sections \
            --prefix="" \
            --output CHANGELOG.md

      - name: Bump version in package files
        run: |
          find . \
            -name "*.el" \
            -exec sed -i -E "s|^(;; Version: ).*\$|\1${{ env.NEXT_VERSION }}|g" {} \;

      - name: Commit and push version changes
        run: |
          git add -- ./\*.el
          git commit \
            --no-verify \
            -m "chore: release v${{ env.NEXT_VERSION }}"
          git push
      
      - name: Create and tag release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            v${{ env.NEXT_VERSION }} \
            --target $(git rev-parse HEAD) \
            -F CHANGELOG.md
