name: Package test

env:
  CACHE_NAME: nix-ts-mode

on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: conao3/setup-cask@master
        with:
          version: snapshot
      
      - name: Install Nix grammar
        run: |
          emacs -batch -l test/scripts/install-nix-grammar.el

      - name: Run tests
        run: make test