name: Package test

env:
  CACHE_NAME: nix-ts-mode

on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
          - release-snapshot
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: conao3/setup-cask@master
        with:
          version: '0.8.4'
      
      - name: Install Nix grammar
        run: |
          emacs -batch \
            --eval="(setq treesit-language-source-alist '((nix "https://github.com/nix-community/tree-sitter-nix")))" \
            --eval="(treesit-install-language-grammar 'nix')"

      - name: Run tests
        run: make test