name: Package test

env:
  CACHE_NAME: nix-ts-mode

on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"

jobs:
  test:
    strategy:
      matrix:
        attr: ["release-snapshot", "snapshot"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_version: 2.16.1
      - uses: cachix/cachix-action@v12
        with:
          name: '${{ env.CACHE_NAME }}'
	  authToken: '${{ secrets.NIX_TS_MODE_CACHIX_TOKEN }}'
	  extraPullNames: emacs-ci
      - run: nix build .#emacs-${{ matrix.attr }}
      - name: Run ERT tests
        run: |
          ./result/bin/emacs \
            --batch \
            --directory $(pwd) \
            --load ert \
            --load ./tests/nix-ts-mode-font-lock-tests.el \
            --funcall ert-run-tests-batch-and-exit